sudo: false
language: java
services:
  - docker
jdk:
  - openjdk8

script:
  - mvn versions:set -DnewVersion=$TRAVIS_TAG
  - docker build -t alex9849/mc-pluginstats-server:$TRAVIS_TAG ./web

deploy:
  provider: script
  script: bash ./travis/docker_deploy.sh
  on:
    tags: true
  overwrite: true