sudo: false
language: java
services:
  - docker
jdk:
  - openjdk8

before_deploy:
  - "mvn versions:set -DnewVersion=$TRAVIS_TAG"
  - "mvn versions:commit"
  - "docker build -t alex9849/mc-pluginstats-server:$TRAVIS_TAG ./web"

deploy:
  provider: script
  script: bash ./.travis/docker_deploy.sh
  on:
    tags: true
  overwrite: true