# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Deploy

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Build project
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}
          mvn versions:commit
      - name: Archive server
        uses: actions/upload-artifact@v2
        with:
          name: Server
          path: web/target/server.jar
  deploy-docker:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: alex9849
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Server
          path: web/target/
      - name: Build images
        run: |
          docker build -t alex9849/mc-pluginstats-server:${GITHUB_REF/refs\/tags\//} ./web
      - name: Push images
        run: docker push alex9849/mc-pluginstats-server --all-tags
